drivers: tee: optee: add include for kernel_arch_interface
Build fails with the following error:
> fatal error: kernel_arch_interface.h: No such file or directory

It was found that required header is placed in
${ZEPHYR_BASE}/kernel/include directory so add it to the CMakeLists file.

Signed-off-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>
Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>
Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>